python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0.1_b1.0_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'

python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0.2_b1.0_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'

python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0.3_b1.0_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'

python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0.1_b0.1_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'

python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0.1_b0.2_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'

python run_planner_tree.py --conversational_LLM='deepseek' --depth=3 --num_generate=1 --num_keep=1 --num_of_mol=200 --task_id=101 --planner='rl_planner' --constraint='strict' --conversation_type='multi' --rl_model_path='results/rl_model_checkpoint/reward_type_add_a0_b0_c1.0_tau0.02general_replay_buffer_mol_strict_101_best_reward_v1.pth'